---
title: "West + Northwest Climate Change Sentiment Analysis"
author: "Umar Abushaban"
date: "10/19/2021"
output:
  html_document:
    toc: yes
    theme: cosmo
    toc_float: yes
  pdf_document:
    toc: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, cache = FALSE)
```

```{r Libraries, include=FALSE}
library(tidyverse)
library(tidytext)
library(ggwordcloud)
library(gutenbergr)
library(textdata)
library(ggplot2)
```


## Regional Climate Change Exploration: {.tabset}

### The Los Angeles Times:

```{r West, echo = FALSE}
# We load in a txt file containing all of the text from The LA Times as a tibble.
LATimesClimate <- tibble(text = read_lines('LA_Times_Climate.txt'))

# Separate the words into individual rows.
LA_Words <-  LATimesClimate %>% unnest_tokens(word, text)
# Removing any stop words.
LA_Words_SW <- LA_Words %>% anti_join(stop_words)
# Counting the frequency of each word in the corpus (entire body of the LA Times articles in the .txt file)
LA_Count <- LA_Words_SW %>% count(word, sort=TRUE)

# Sentiment analysis. We use three different sentiment data sets: affin, nrc, and bing.
LASentiment_affin <- LA_Words %>%
  inner_join(get_sentiments("afinn"))

LASentiment_nrc <- LA_Words %>%
  inner_join(get_sentiments("nrc"))

LASentiment_bing <- LA_Words %>%
  inner_join(get_sentiments("bing"))

# Taking a look at the bing sentiment analysis, which just gives us a sense of the ratio between positive and negative words.
cat("Bing Sentiment Analysis:")
table(LASentiment_bing$sentiment)
# We can compare the ratios of positive to negative words in different regions.
cat(paste("Positive Word to Negative Word Ratio:", 
          as.character(round((1082/763 ),digits = 2))))


# The nrc sentiment analysis is more complex, and ranks words based on different characteristics beyond positive and negative.
cat("NRC Sentiment Analysis")
table(LASentiment_nrc$sentiment)
ggplot(LASentiment_nrc, aes(x = sentiment)) + geom_bar()

# Finally, we can look at the affin sentiment (which ranks how positive a word is on a scale of -5 to 5) and determine the frequency of more positive words.
cat("Affin Sentiment Analysis")
(ggplot(data = LASentiment_affin, 
       aes(x=value))+
  geom_bar()+
  ggtitle("The Los Angeles Times Sentiment Range")+
  theme_minimal())

# Word Cloud
set.seed(42)
ggplot(LA_Count[1:50,], aes(label = word, size = n )) + geom_text_wordcloud(rm_outside = TRUE) + scale_size(range = c(2,12)) + theme_minimal()
```

### The Seattle Times
```{r Northwest, echo = FALSE}




# Loading in the data:
SeattleTimesClimate <- tibble(text = read_lines('Seattle_Times_Climate.txt'))

# Seperating out the words into individual rows.
Seattle_Words <-  SeattleTimesClimate %>% unnest_tokens(word, text)
# removing any stop words.
Seattle_Words_SW <- Seattle_Words %>% anti_join(stop_words)
# After removing the stop words, we can see that the total word count has almost exactly halved.

# Next, we count the frequency of each word in the corpus.
Seattle_Count <- Seattle_Words_SW %>% count(word, sort=TRUE)


# Sentiment Analysis
SeattleSentiment_affin <- Seattle_Words %>%
  inner_join(get_sentiments("afinn"))

SeattleSentiment_nrc <- Seattle_Words %>%
  inner_join(get_sentiments("nrc"))

SeattleSentiment_bing <- Seattle_Words %>%
  inner_join(get_sentiments("bing"))

# Taking a look at the bing sentiment analysis, which just gives us a sense of the ratio between positive and negative words.
cat("Bing Sentiment Analysis:")
table(SeattleSentiment_bing$sentiment)
# We can compare the ratios of positive to negative words in different regions.
cat(paste("Positive Word to Negative Word Ratio:", 
          as.character(round((577/547),digits = 2))))
# The positive to negative word ratio is higher in The Seattle Times compared to the Los Angeles Times, so the conversation surrounding climate change has a more positive sentiment in this region.

# The nrc sentiment analysis ranks words based on different characteristics beyond positive and negative.
cat("NRC Sentiment Analysis")
ggplot(SeattleSentiment_nrc, aes(x = sentiment)) + geom_bar()
cat("Affin Sentiment Analysis")
(ggplot(data = SeattleSentiment_affin, 
       aes(x=value))+
  geom_bar()+
  ggtitle("The Seattle Times Climate Sentiment Range")+
  theme_minimal())

# Word Cloud
set.seed(42)
ggplot(Seattle_Count[1:50,], aes(label = word, size = n )) + geom_text_wordcloud(rm_outside = TRUE) + scale_size(range = c(2,12)) + theme_minimal()

```